package echo.client.ui;

import echo.client.GameClient;

/**
 *
 * @author Vincent Cantin
 */
public class EchoFrame extends javax.swing.JFrame {

  private GameClient gameClient;

  public EchoFrame(GameClient gameClient) {
    this.gameClient = gameClient;
    
    initComponents();
  }

  public void notifyEchoSaidSomething(String textMessage) {
    fromServerTextArea.append("echoClient.notifyEchoSaidSomething(\"" + textMessage + "\");\n");
  }

  private void sendMessageInTextField() {
    String textMessage = toServerTextField.getText();
    
    if (!textMessage.isEmpty()) {
      gameClient.echoServerProxy.requestSaySomethingToEcho(textMessage);
      toServerTextField.setText("");
      toServerTextArea.append("echoServerProxy.requestSaySomethingToEcho(\"" + textMessage + "\");\n");
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
    javax.swing.JButton sendToServerButton = new javax.swing.JButton();
    toServerTextField = new javax.swing.JTextField();
    javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
    toServerTextArea = new javax.swing.JTextArea();
    javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
    javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    fromServerTextArea = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Small Echo Sample");
    setMinimumSize(new java.awt.Dimension(600, 400));

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Messages sent to the echo server"));

    sendToServerButton.setText("Send");
    sendToServerButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sendToServerButtonActionPerformed(evt);
      }
    });

    toServerTextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        toServerTextFieldActionPerformed(evt);
      }
    });

    toServerTextArea.setEditable(false);
    jScrollPane2.setViewportView(toServerTextArea);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(toServerTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sendToServerButton)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(sendToServerButton)
          .addComponent(toServerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        .addContainerGap())
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Messages received from the echo server"));

    fromServerTextArea.setEditable(false);
    jScrollPane1.setViewportView(fromServerTextArea);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void toServerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toServerTextFieldActionPerformed
    sendMessageInTextField();
  }//GEN-LAST:event_toServerTextFieldActionPerformed

  private void sendToServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToServerButtonActionPerformed
    sendMessageInTextField();
  }//GEN-LAST:event_sendToServerButtonActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea fromServerTextArea;
  private javax.swing.JTextArea toServerTextArea;
  private javax.swing.JTextField toServerTextField;
  // End of variables declaration//GEN-END:variables
}
